# Generated by Django 4.0.4 on 2022-05-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='full_workout',
            name='workouts',
        ),
        migrations.AddField(
            model_name='full_workout',
            name='workouts',
            field=models.ManyToManyField(to='workouts.workout'),
        ),
    ]
