# Generated by Django 4.0.4 on 2022-05-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_full_workout_workouts_full_workout_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
