# Generated by Django 4.0.4 on 2022-05-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='name',
        ),
    ]
